### ISSUE TITLE
Textfield

### ISSUE THREAD

**Issue by imanshu15** [nickidebruyn/galago#1]
I am trying to use a TextField to get a user input. But when ever i presse a key i get this error.

Uncaught exception thrown in Thread[jME3 Main,5,main]
IncompatibleClassChangeError: Expecting non-static method com.jme3.input.KeyNames.getName(I)Ljava/lang/String;

I cant type anything. Is there anyway to fix this?

**Comment by nickidebruyn** [comment]
Can you show me some sample code of what you do?

**Comment by imanshu15** [comment]
![screenshot 9](https://cloud.githubusercontent.com/assets/15451073/26791558/23ee17a0-4a35-11e7-88a3-e83bb73dbea6.png)

This is where i set up my textbox. I dont know how to implement key board listener exactly.

![screenshot 10](https://cloud.githubusercontent.com/assets/15451073/26791589/3a942918-4a35-11e7-9752-d86dfaf016f2.png)

And when ever i try to type something on textField i get this error. Would be really gratefull if u could help me out on this .thank you

**Comment by nickidebruyn** [comment]
If you are using jME3.1 you need to make use of the build Galago-3.1.1.jar
If you are on jME3.0 you can make use of Galago-3.0.1.jar
Here: https://github.com/nickidebruyn/galago/tree/master/Releases

**Comment by imanshu15** [comment]
Thank you. It works now
